const level1 = new Level(
    enemies = [
        new PufferFish(),
        new PufferFish(),
        new PufferFishRed(),
        new PufferFishRed(),
        new JellyFish(),
        new JellyFish(),
        new JellyFishGreen(),
        new JellyFishYellow(),
        new Endboss(),
    ],
    backgroundObjects = [
        new BackgroundObject('img/3. Background/Layers/5. Water/L1.png', 0, 0),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/L1.png', 0, 0),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/L1.png', 0, 0),
        new BackgroundObject('img/3. Background/Layers/2. Floor/L1.png', 0, 0),
        new BackgroundObject('img/3. Background/Legacy/Layers/1. Light/1.png', 0, 0),
        new BackgroundObject('img/3. Background/Layers/5. Water/L2.png', 720, 0),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/L2.png', 720, 0),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/L2.png', 720, 0),
        new BackgroundObject('img/3. Background/Layers/2. Floor/L2.png', 720, 0),
        new BackgroundObject('img/3. Background/Legacy/Layers/1. Light/2.png', 720, 0),
        new BackgroundObject('img/3. Background/Layers/5. Water/L1.png', 720*2, 0),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/L1.png', 720*2, 0),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/L1.png', 720*2, 0),
        new BackgroundObject('img/3. Background/Layers/2. Floor/L1.png', 720*2, 0),
        new BackgroundObject('img/3. Background/Legacy/Layers/1. Light/1.png', 720*2, 0),
        new BackgroundObject('img/3. Background/Layers/5. Water/L2.png', 720*3, 0),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/L2.png', 720*3, 0),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/L2.png', 720*3, 0),
        new BackgroundObject('img/3. Background/Layers/2. Floor/L2.png', 720*3, 0),
        new BackgroundObject('img/3. Background/Legacy/Layers/1. Light/2.png', 720*3, 0),
        new BackgroundObject('img/3. Background/Layers/5. Water/L1.png', 720*4, 0),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/L1.png', 720*4, 0),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/L1.png', 720*4, 0),
        new BackgroundObject('img/3. Background/Layers/2. Floor/L1.png', 720*4, 0),
        new BackgroundObject('img/3. Background/Legacy/Layers/1. Light/1.png', 720*4, 0),
    ],
);